In [15]:
import pandas as pd
import numpy as np

A = np.array([[2,3,5,4,8],[8,5,4,7,8],[8,5,4,7,8],[8,5,4,7,8],[8,5,4,7,8],[8,5,4,7,8],[8,5,4,7,8]])
B = np.array([[4,6,10,8,16],[4,2.5,2,3.5,4,],[8,5,4,7,8],[8,5,4,7,8],[8,5,4,7,8]])

Martix1 = []
Matrix1 = A
Martix2 = []
Matrix2 = B

print(Matrix1)
print(Matrix2)

#Matrix3 = Matrix1 + Matrix2
#C= A * B

print(Matrix3)
print(C)

Matrix1.sum(axis=0)
Matrix2.sum(axis=1)

#Matrix3 = Matrix1 + Matrix2
#C= A * B

print(Matrix1)
print(Matrix2)
print(Matrix3)

print(A)
print(B)
print(C)



[[2 3 5 4 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]]
[[ 4.   6.  10.   8.  16. ]
 [ 4.   2.5  2.   3.5  4. ]
 [ 8.   5.   4.   7.   8. ]
 [ 8.   5.   4.   7.   8. ]
 [ 8.   5.   4.   7.   8. ]]
[list([2, 3, 5, 4, 8, 4, 6, 10, 8, 16])
 list([8, 5, 4, 7, 8, 9, 1, 4, 2.5, 2, 3.5, 4, 4.5, 0.5])]
[list([2, 3, 5, 4, 8, 4, 6, 10, 8, 16])
 list([8, 5, 4, 7, 8, 9, 1, 4, 2.5, 2, 3.5, 4, 4.5, 0.5])]
[[2 3 5 4 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]]
[[ 4.   6.  10.   8.  16. ]
 [ 4.   2.5  2.   3.5  4. ]
 [ 8.   5.   4.   7.   8. ]
 [ 8.   5.   4.   7.   8. ]
 [ 8.   5.   4.   7.   8. ]]
[list([2, 3, 5, 4, 8, 4, 6, 10, 8, 16])
 list([8, 5, 4, 7, 8, 9, 1, 4, 2.5, 2, 3.5, 4, 4.5, 0.5])]
[[2 3 5 4 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]
 [8 5 4 7 8]]
[[ 4.   6.  10.   8.  16. ]
 [ 4.   2.5  2.   3.5  4. ]
 [ 8.   5.   4.   7.   8. ]
 [ 8.   5.   4.   7.   8. ]
 [ 8.   5.   4.   7.   8. ]]
[lis